<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="BO" failures="6" tests="9" name="Smoke Test" time="159.385" errors="0" timestamp="2023-03-06T18:34:53 EST">
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="22.604">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="21.639">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="23.33">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="21.261">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="22.119">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeTest" name="addEmployeeTest" time="3.062"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="1.207"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.103"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.847">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserInvalidPassword(LoginTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validUserInvalidPassword -->
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.0">
    <ignored/>
  </testcase> <!-- userLogin -->
</testsuite> <!-- Smoke Test -->
